import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';

const supervisor='00000000-0000-0000-0000-000000000001', observer='00000000-0000-0000-0000-000000000002';
test('migración, permisos, importación atómica y cierre estable', async()=>{
 const db=new PGlite();
 await db.exec(`create role anon; create role authenticated; create schema auth; create schema storage;
 create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
 grant usage on schema public,auth,storage to authenticated,anon;
 create table perfiles(id uuid primary key,activo boolean,rol text,es_desarrollador boolean);
 insert into perfiles values('${supervisor}',true,'supervisor',false),('${observer}',true,'observador',false);
 create table eventos_historial(id uuid primary key default gen_random_uuid(),locomotora_codigo text,fecha date,hora time,tipo text,preventivo_codigo text,titulo text,descripcion text,responsable text,especialidad text,criticidad text,origen text,metadata jsonb default '{}',anulado boolean default false,created_at timestamptz default now(),updated_at timestamptz default now());
 create table adjuntos_evento(id uuid primary key default gen_random_uuid(),evento_id uuid references eventos_historial(id));
 create table importaciones_libro(id uuid primary key default gen_random_uuid());
 create table locomotoras(id uuid primary key default gen_random_uuid(),codigo text);
 create table storage.buckets(id text primary key,public boolean); insert into storage.buckets values('eventos-adjuntos',true);
 create table storage.objects(id uuid,bucket_id text); alter table storage.objects enable row level security;
 grant select on perfiles to authenticated;`);
 await db.exec(await readFile('supabase/migrations/20260629_avances_mantenimiento.sql','utf8'));
 const migration=await readFile('supabase/migrations/20260927_seguimiento_integrado.sql','utf8');
 await db.exec(migration);
 await db.exec(migration); // repeatable
 await db.exec(await readFile('supabase/migrations/20260927_cerrar_ejecucion_anonima_funciones.sql','utf8'));
 await db.exec(await readFile('supabase/migrations/20260927_permitir_recalculo_interno.sql','utf8'));
 await db.exec(await readFile('supabase/migrations/20260929194849_jornada_confirmada.sql','utf8'));
 const delays=await readFile('supabase/migrations/20261004233410_demoras_maniobras_nueva_falla.sql','utf8');await db.exec(delays);await db.exec(delays);
 const dailyClosure=await readFile('supabase/migrations/20261005113308_daily_state_closes_maintenance.sql','utf8');await db.exec(dailyClosure);await db.exec(dailyClosure);
 assert.equal((await db.query("select has_function_privilege('anon','public.mr_access(boolean)','EXECUTE') as allowed")).rows[0].allowed,false);
 await db.exec(`set role authenticated; set request.jwt.claim.sub = '${supervisor}';`);
 const e={locomotoraCodigo:'E701',fecha:'2020-01-06',hora:'06:00',tipo:'correctivo',titulo:'Prueba sintética',descripcion:'Ejemplo de validación',responsable:'Turno fijo',especialidad:'Mecanica',estadoMantenimiento:'finalizado',fechaCierre:'2020-01-07',horaCierre:'14:00',metadata:{pilotSourceId:'test-one',seguimiento:{location:'Boulogne',detentionStart:'2020-01-06',system:'Bogie',component:'Prueba'}}};
 const a={fecha:'2020-01-06',hora:'06:00',descripcion:'Ejemplo',responsable:'Turno fijo',metadata:{seguimiento:{activity:'trabajo',period:'Mañana'}}};
 const payload=[{event:e,actualizaciones:[a]}];
 const call=async p => db.query('select public.importar_seguimiento_piloto($1::jsonb) as count',[JSON.stringify(p)]);
 assert.equal((await call(payload)).rows[0].count,1);
 assert.equal((await call(payload)).rows[0].count,0);
 let rows=(await db.query('select * from eventos_historial')).rows;
 assert.equal(rows.length,1);assert.equal(rows[0].estado_mantenimiento,'finalizado');assert.equal(rows[0].fecha_cierre.toISOString().slice(0,10),'2020-01-07');
 const malformed=structuredClone(payload);malformed[0].event.metadata.pilotSourceId='test-two';malformed[0].event.locomotoraCodigo='E702';malformed[0].actualizaciones[0].metadata.seguimiento.period='Tarde';
 await assert.rejects(call(malformed),/Turno fijo/);assert.equal((await db.query('select count(*) as n from eventos_historial')).rows[0].n,1);
 for(const cause of ['Man','FA']) {
  const delayed=structuredClone(payload);delayed[0].event.metadata.pilotSourceId=`delay-${cause}`;
  delayed[0].actualizaciones[0].metadata.seguimiento={activity:'mixto',period:'Mañana',cause};
  assert.equal((await call(delayed)).rows[0].count,1);
 }
 const invalidCause=structuredClone(payload);invalidCause[0].event.metadata.pilotSourceId='delay-invalid';invalidCause[0].actualizaciones[0].metadata.seguimiento={activity:'mixto',period:'Mañana',cause:'INVALID'};
 await assert.rejects(call(invalidCause),/causa de demora/);
 const day=(await db.query("select to_char(now() at time zone 'America/Argentina/Buenos_Aires','YYYY-MM-DD') as day")).rows[0].day;
 const openEvent={...e,fecha:day,estadoMantenimiento:'en_curso',fechaCierre:null,metadata:{pilotSourceId:'today-open',seguimiento:{...e.metadata.seguimiento,detentionStart:day}}};
 const mixed={...a,fecha:day,metadata:{seguimiento:{activity:'mixto',period:'Mañana',cause:'CAP',usefulFraction:.5,allocationNote:'Mitad trabajo, mitad espera'}}};
 await assert.rejects(call([{event:openEvent,actualizaciones:[mixed]}]),/día sigue/);
 mixed.metadata.seguimiento.dayComplete=true;
 await call([{event:openEvent,actualizaciones:[mixed]}]);
 assert.equal((await db.query("select estado_mantenimiento from eventos_historial where metadata->>'pilotSourceId'='today-open'")).rows[0].estado_mantenimiento,'en_curso');
 await db.exec(`set request.jwt.claim.sub = '${observer}';`);
 assert.equal((await db.query('select count(*) as n from eventos_historial')).rows[0].n,4);
 await assert.rejects(call([{event:{...e,metadata:{...e.metadata,pilotSourceId:'third'}},actualizaciones:[]}]),/permisos/);
 await db.exec('reset role; set role anon;');
 await assert.rejects(db.query('select * from eventos_historial'),/permission denied/);
 await db.exec(`reset role; set role authenticated; set request.jwt.claim.sub = '00000000-0000-0000-0000-000000000099';`);
 assert.equal((await db.query('select * from eventos_historial')).rows.length,0);
 await db.exec(`reset role; set role authenticated; set request.jwt.claim.sub = '${supervisor}';`);
 const createOpen=async(unit,from='2020-01-06')=>(await db.query(`insert into eventos_historial(locomotora_codigo,fecha,hora,tipo,titulo,descripcion,responsable,estado_mantenimiento,metadata) values($1,$2,'06:00','correctivo','Prueba','Registro sintético','Turno fijo','en_curso',$3::jsonb) returning id`,[unit,from,JSON.stringify({seguimiento:{location:'Boulogne',detentionStart:from,system:'Bogie',component:'Prueba',outcome:'continua'}})])).rows[0].id;
 const first=await createOpen('EM01'),second=await createOpen('EM01');
 const report=JSON.stringify({dailyState:{reportedState:'operativa',state:'detenida',conflict:true,observation:''}});
 const imported=(await db.query(`insert into eventos_historial(locomotora_codigo,fecha,hora,tipo,titulo,responsable,metadata) values('EM01','2020-01-07','06:00','otro','Estado diario','Parte diario',$1::jsonb) returning id,metadata`,[report])).rows[0];
 assert.equal(imported.metadata.dailyState.state,'operativa');assert.equal(imported.metadata.dailyState.conflict,false);assert.equal(imported.metadata.dailyState.closedMaintenanceIds.length,2);
 const closed=(await db.query('select estado_mantenimiento,fecha_cierre,hora_cierre,metadata from eventos_historial where id=any($1::uuid[])',[[first,second]])).rows;
 assert.ok(closed.every(r=>r.estado_mantenimiento==='finalizado'&&r.hora_cierre==='06:00:00'&&r.metadata.seguimiento.outcome==='operativa'));
 const closures=(await db.query("select * from actualizaciones_evento where evento_id=any($1::uuid[])",[[first,second]])).rows;assert.equal(closures.length,2);assert.ok(closures.every(r=>r.tipo_actualizacion==='cierre'&&r.metadata.seguimiento.activity==='sin_dato'&&!r.metadata.seguimiento.workDurationDays&&r.metadata.dailyStateClosure.confirmedBy===supervisor));
 await db.query('update eventos_historial set metadata=metadata where id=$1',[imported.id]);assert.equal((await db.query('select count(*)::int as n from actualizaciones_evento where evento_id=any($1::uuid[])',[[first,second]])).rows[0].n,2);
 const future=await createOpen('E703','2020-01-08');await db.query(`insert into eventos_historial(locomotora_codigo,fecha,hora,tipo,metadata) values('E703','2020-01-07','06:00','otro',$1::jsonb)`,[report]);assert.equal((await db.query('select estado_mantenimiento from eventos_historial where id=$1',[future])).rows[0].estado_mantenimiento,'en_curso');
 const later=await createOpen('E704');await db.query(`insert into actualizaciones_evento(evento_id,fecha,hora,tipo_actualizacion,descripcion,metadata) values($1,'2020-01-08','06:00','observacion','Novedad posterior',$2::jsonb)`,[later,JSON.stringify({seguimiento:{activity:'sin_dato'}})]);
 await db.query(`insert into actualizaciones_evento(evento_id,fecha,hora,tipo_actualizacion,descripcion,responsable,metadata) values($1,'2020-01-08','06:00','avance','Trabajo posterior','Turno fijo',$2::jsonb)`,[later,JSON.stringify({seguimiento:{activity:'trabajo',period:'Mañana'}})]);
 const old=(await db.query(`insert into eventos_historial(locomotora_codigo,fecha,hora,tipo,metadata) values('E704','2020-01-07','06:00','otro',$1::jsonb) returning metadata`,[report])).rows[0];assert.equal(old.metadata.dailyState.state,'detenida');assert.equal((await db.query('select estado_mantenimiento from eventos_historial where id=$1',[later])).rows[0].estado_mantenimiento,'en_curso');
 const atomic=await createOpen('E705');await assert.rejects(db.query(`insert into eventos_historial(locomotora_codigo,fecha,hora,tipo,metadata) values('E705','2020-01-07','06:00','otro',$1::jsonb),('E706','2999-01-01','06:00','correctivo',$2::jsonb)`,[report,JSON.stringify({seguimiento:{location:'Boulogne',detentionStart:'2999-01-01',system:'Bogie',component:'Prueba'}})]),/Fechas/);assert.equal((await db.query('select estado_mantenimiento from eventos_historial where id=$1',[atomic])).rows[0].estado_mantenimiento,'en_curso');assert.equal((await db.query('select count(*)::int as n from actualizaciones_evento where evento_id=$1',[atomic])).rows[0].n,0);
 // A completed historical E shift corrects the daily report's later automatic closure.
 await db.exec('reset role;');
 await db.exec(await readFile('supabase/migrations/20261006120958_final_light_shift_overrides_daily_closure.sql','utf8'));
 await db.exec(`set role authenticated; set request.jwt.claim.sub = '${supervisor}';`);
 const lightId=(await db.query(`insert into eventos_historial(locomotora_codigo,fecha,hora,tipo,preventivo_codigo,titulo,responsable,estado_mantenimiento,metadata) values('E713','2020-01-06','06:00','preventivo','E','Preventivo E','Turno rotativo','en_curso',$1::jsonb) returning id`,[JSON.stringify({seguimiento:{detentionStart:'2020-01-06',location:'Boulogne'}})])).rows[0].id;
 await db.query(`insert into eventos_historial(locomotora_codigo,fecha,hora,tipo,metadata) values('E713','2020-01-07','06:00','otro',$1::jsonb)`,[report]);
 const finalShift={seguimiento:{activity:'trabajo',period:'Mañana',shiftNumber:1,shiftFinished:true,additionalShiftRequired:false,completedFinalShift:true,outcome:'operativa',outcomeConfirmed:true}};
 await db.query(`insert into actualizaciones_evento(evento_id,fecha,hora,tipo_actualizacion,descripcion,responsable,metadata) values($1,'2020-01-06','14:00','observacion','Sin novedades','Turno rotativo',$2::jsonb)`,[lightId,JSON.stringify(finalShift)]);
 const corrected=(await db.query('select estado_mantenimiento,fecha_cierre,hora_cierre,metadata from eventos_historial where id=$1',[lightId])).rows[0];
 assert.equal(corrected.estado_mantenimiento,'finalizado');assert.equal(corrected.fecha_cierre.toISOString().slice(0,10),'2020-01-06');assert.equal(corrected.hora_cierre,'14:00:00');assert.equal(corrected.metadata.seguimiento.availableDate,'2020-01-06');
 await db.query(`update actualizaciones_evento set descripcion='Sin novedades confirmadas' where evento_id=$1 and tipo_actualizacion='observacion'`,[lightId]);
 assert.equal((await db.query('select hora_cierre from eventos_historial where id=$1',[lightId])).rows[0].hora_cierre,'14:00:00');
 await db.close();
});
