import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { PGlite } from '@electric-sql/pglite';

const supervisor='00000000-0000-0000-0000-000000000001', observer='00000000-0000-0000-0000-000000000002';
test('migración, permisos, importación atómica y cierre estable', async()=>{
 const db=new PGlite();
 await db.exec(`create role anon; create role authenticated; create schema auth; create schema storage;
 create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
 grant usage on schema public,auth,storage to authenticated,anon;
 create table perfiles(id uuid primary key,activo boolean,rol text,es_desarrollador boolean);
 insert into perfiles values('${supervisor}',true,'supervisor',false),('${observer}',true,'observador',false);
 create table eventos_historial(id uuid primary key default gen_random_uuid(),locomotora_codigo text,fecha date,hora time,tipo text,preventivo_codigo text,titulo text,descripcion text,responsable text,especialidad text,criticidad text,origen text,metadata jsonb default '{}',anulado boolean default false,created_at timestamptz default now(),updated_at timestamptz default now());
 create table adjuntos_evento(id uuid primary key default gen_random_uuid(),evento_id uuid references eventos_historial(id));
 create table importaciones_libro(id uuid primary key default gen_random_uuid());
 create table locomotoras(id uuid primary key default gen_random_uuid(),codigo text);
 create table storage.buckets(id text primary key,public boolean); insert into storage.buckets values('eventos-adjuntos',true);
 create table storage.objects(id uuid,bucket_id text); alter table storage.objects enable row level security;
 grant select on perfiles to authenticated;`);
 await db.exec(await readFile('supabase/migrations/20260629_avances_mantenimiento.sql','utf8'));
 const migration=await readFile('supabase/migrations/20260927_seguimiento_integrado.sql','utf8');
 await db.exec(migration);
 await db.exec(migration); // repeatable
 await db.exec(await readFile('supabase/migrations/20260927_cerrar_ejecucion_anonima_funciones.sql','utf8'));
 await db.exec(await readFile('supabase/migrations/20260927_permitir_recalculo_interno.sql','utf8'));
 assert.equal((await db.query("select has_function_privilege('anon','public.mr_access(boolean)','EXECUTE') as allowed")).rows[0].allowed,false);
 await db.exec(`set role authenticated; set request.jwt.claim.sub = '${supervisor}';`);
 const e={locomotoraCodigo:'E701',fecha:'2020-01-06',hora:'06:00',tipo:'correctivo',titulo:'Prueba sintética',descripcion:'Ejemplo de validación',responsable:'Turno fijo',especialidad:'Mecanica',estadoMantenimiento:'finalizado',fechaCierre:'2020-01-07',horaCierre:'14:00',metadata:{pilotSourceId:'test-one',seguimiento:{location:'Boulogne',detentionStart:'2020-01-06',system:'Bogie',component:'Prueba'}}};
 const a={fecha:'2020-01-06',hora:'06:00',descripcion:'Ejemplo',responsable:'Turno fijo',metadata:{seguimiento:{activity:'trabajo',period:'Mañana'}}};
 const payload=[{event:e,actualizaciones:[a]}];
 const call=async p => db.query('select public.importar_seguimiento_piloto($1::jsonb) as count',[JSON.stringify(p)]);
 assert.equal((await call(payload)).rows[0].count,1);
 assert.equal((await call(payload)).rows[0].count,0);
 let rows=(await db.query('select * from eventos_historial')).rows;
 assert.equal(rows.length,1);assert.equal(rows[0].estado_mantenimiento,'finalizado');assert.equal(rows[0].fecha_cierre.toISOString().slice(0,10),'2020-01-07');
 const malformed=structuredClone(payload);malformed[0].event.metadata.pilotSourceId='test-two';malformed[0].event.locomotoraCodigo='E702';malformed[0].actualizaciones[0].metadata.seguimiento.period='Tarde';
 await assert.rejects(call(malformed),/Turno fijo/);assert.equal((await db.query('select count(*) as n from eventos_historial')).rows[0].n,1);
 await db.exec(`set request.jwt.claim.sub = '${observer}';`);
 assert.equal((await db.query('select count(*) as n from eventos_historial')).rows[0].n,1);
 await assert.rejects(call([{event:{...e,metadata:{...e.metadata,pilotSourceId:'third'}},actualizaciones:[]}]),/permisos/);
 await db.exec('reset role; set role anon;');
 await assert.rejects(db.query('select * from eventos_historial'),/permission denied/);
 await db.exec(`reset role; set role authenticated; set request.jwt.claim.sub = '00000000-0000-0000-0000-000000000099';`);
 assert.equal((await db.query('select * from eventos_historial')).rows.length,0);
 await db.close();
});
