import { test, expect } from '@playwright/test';
const event={id:'example',locomotora_codigo:'E701',fecha:'2026-09-24',hora:'06:00',tipo:'correctivo',titulo:'Correctivo de prueba',descripcion:'Revisión sintética del componente',responsable:'Turno fijo',estado_mantenimiento:'finalizado',fecha_cierre:'2026-09-25',metadata:{seguimiento:{detentionStart:'2026-09-24',location:'Boulogne',system:'Bogie',component:'Componente de prueba'}}};
const updates=[{id:'first',evento_id:'example',fecha:'2026-09-24',hora:'06:00',tipo_actualizacion:'observacion',descripcion:'Revisión con espera de recurso',responsable:'Turno fijo',metadata:{seguimiento:{activity:'mixto',period:'Mañana',cause:'CAP',usefulFraction:.5,allocationNote:'Media jornada de espera'}}},{id:'second',evento_id:'example',fecha:'2026-09-25',hora:'06:00',tipo_actualizacion:'observacion',descripcion:'Trabajo terminado',responsable:'Turno fijo',metadata:{seguimiento:{activity:'trabajo',period:'Mañana'}}}];
test('semana, detalle, eficiencia, corrección y CSV',async({page})=>{
 await page.route('http://127.0.0.1:54321/**',route=>route.fulfill({json:route.request().url().includes('seguimiento_version') ? 1 : route.request().url().includes('actualizaciones_evento') ? updates : [event]}));
 await page.goto('/tests/seguimiento.html');
 await page.getByLabel('Semana del').fill('2026-09-21');
 const bar=page.locator('.tracking-bar');await expect(bar).toHaveCount(1);await expect(bar).toHaveCSS('grid-column-end','span 2');
 await expect(page.getByRole('heading',{name:'Semana 39'})).toBeVisible();
 await page.getByRole('button',{name:'Ver día 24/09/2026',exact:true}).click();
 await expect(page.getByRole('region',{name:'Actividad del 24/09/2026'}).getByText('Revisión con espera de recurso')).toBeVisible();
 await expect(page.getByRole('button',{name:'Eficiencia',exact:true})).toHaveCount(0);
 await expect(page.getByRole('button',{name:'Actualizar',exact:true})).toHaveCount(0);
 await bar.click();await expect(page.getByRole('heading',{name:'Eficiencia del mantenimiento'})).toBeVisible();
 await expect(page.getByText('75 %',{exact:true})).toBeVisible();
 await expect(page.getByRole('img',{name:'1,5 días útiles, 0,5 perdidos y 0 sin información'})).toBeVisible();
 await page.screenshot({path:'/workspace/scratch/7ec95ebdf471/mantenimiento-detalle.png',fullPage:true});
 await page.locator('.maintenance-efficiency').scrollIntoViewIfNeeded();
 await page.screenshot({path:'/workspace/scratch/7ec95ebdf471/mantenimiento-eficiencia.png',fullPage:true});
 await page.getByRole('button',{name:'Corregir / completar registro'}).first().click();await expect(page.getByRole('button',{name:'Trabajo y demora',exact:true})).toHaveAttribute('aria-pressed','true');
 await expect(page.getByLabel('Estado posterior de la máquina')).toBeVisible();
 await page.getByRole('button',{name:'Cerrar',exact:true}).click();await page.getByRole('button',{name:'Cerrar detalle'}).click();
 await page.getByText('Exportar CSV',{exact:true}).click();
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Indicadores de la semana',exact:true}).click();expect((await download).suggestedFilename()).toBe('eficiencia-2026-09-21.csv');
 await page.getByText('Exportar CSV',{exact:true}).click();
 await page.screenshot({path:'/workspace/scratch/7ec95ebdf471/mantenimientos-semana.png',fullPage:true});
 await page.getByRole('button',{name:'+ Registrar mantenimiento'}).click();await page.getByLabel('Tipo de evento').selectOption('preventivo');await expect(page.getByText(/Locomotora completa · turno rotativo/)).toBeVisible();
 await expect(page.getByLabel('¿Qué sistema estamos atacando?')).toHaveCount(0);
 await page.getByLabel('Tipo de evento').selectOption('correctivo');await expect(page.getByLabel('¿Qué sistema estamos atacando?')).toBeVisible();
});
